"""
SHIELD — Statistical Hardening & Intelligence Engine for Live Deployment (Agent 3)
====================================================================================
Stress-tests and validates strategies generated by FORGE, protecting
against curve-fitting and ruin before live deployment.

This agent:
    1. Backtests each strategy on historical data
    2. Optimizes parameters (SL, TP, filters, thresholds)
    3. Runs Monte Carlo simulation for robustness (1000 paths)
    4. Performs walk-forward analysis for OOS validation (5 windows)
    5. Produces an OptimizationResult with best configuration
"""

import logging
import itertools
import json
import os
import sys
import numpy as np
from pathlib import Path
from datetime import datetime
from typing import List, Optional, Dict, Any, Callable, Tuple

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from ai_learning.config import (
    PARAM_RANGES, MIN_WIN_RATE, MIN_PROFIT_FACTOR,
    MAX_DRAWDOWN_PCT, MIN_EXPECTANCY_R, EXPORTS_DIR,
    BACKTEST_LOOKBACK_DAYS,
)
from ai_learning.data.schemas import (
    StrategyRule, OptimizationResult, TradingStyleProfile,
)
from ai_learning.data.trade_store import TradeStore
from ai_learning.strategy.rule_engine import RuleEngine, RuleEvaluator
from ai_learning.optimization.backtester import Backtester, BacktestResult
from ai_learning.optimization.monte_carlo import MonteCarloAnalyzer, WalkForwardAnalyzer

log = logging.getLogger("ai_learning.SHIELD")


class SHIELD:
    """
    SHIELD (Agent 3): Stress-tests, optimizes, and validates FORGE-generated strategies.

    Usage:
        agent3 = SHIELD()

        # Optimize a single strategy
        result = agent3.optimize_strategy(
            rule, candles_5m, candles_15m
        )
        print(result.to_dict())

        # Optimize all strategies
        results = agent3.optimize_all(rules, candles_data)
    """

    def __init__(self, store: Optional[TradeStore] = None):
        self.store = store or TradeStore()
        self.backtester = Backtester()
        self.mc_analyzer = MonteCarloAnalyzer()
        self.wf_analyzer = WalkForwardAnalyzer()

    # ──────────────────────────────────────────────────────────────────
    #  Single Strategy Optimization
    # ──────────────────────────────────────────────────────────────────

    def optimize_strategy(
        self,
        rule: StrategyRule,
        candles: List[dict],
        signal_func: Callable,
        htf_candles: Optional[List[dict]] = None,
        param_ranges: Optional[Dict] = None,
    ) -> OptimizationResult:
        """
        Full optimization pipeline for one strategy.

        Args:
            rule: StrategyRule from Agent 2
            candles: Historical candle data (5m)
            signal_func: Signal detection function
            htf_candles: Higher timeframe context
            param_ranges: Parameter ranges to optimize

        Returns:
            OptimizationResult with best params and metrics
        """
        strategy_name = rule.strategy_name
        log.info(f"Optimizing strategy: {strategy_name}")

        # ─── Step 1: Baseline Backtest ────────────────────────────
        log.info("  Step 1: Baseline backtest...")
        baseline = self.backtester.run(
            candles, signal_func, strategy_name, {}
        )
        log.info(f"  Baseline: {baseline.total_trades} trades, "
                 f"WR={baseline.win_rate:.1%}, PF={baseline.profit_factor:.2f}")

        # ─── Step 2: Parameter Optimization ───────────────────────
        log.info("  Step 2: Parameter optimization...")
        ranges = param_ranges or PARAM_RANGES
        best_params, best_backtest = self._grid_search(
            candles, signal_func, strategy_name, ranges
        )
        log.info(f"  Best params: {best_params}")
        log.info(f"  Optimized: {best_backtest.total_trades} trades, "
                 f"WR={best_backtest.win_rate:.1%}, "
                 f"PF={best_backtest.profit_factor:.2f}")

        # ─── Step 3: Monte Carlo ──────────────────────────────────
        log.info("  Step 3: Monte Carlo simulation...")
        mc = self.mc_analyzer.analyze(best_backtest)

        # ─── Step 4: Walk-Forward ─────────────────────────────────
        log.info("  Step 4: Walk-forward analysis...")
        wf = self.wf_analyzer.analyze(
            candles, signal_func, self.backtester,
            strategy_name, best_params
        )

        # ─── Step 5: Robustness Assessment ───────────────────────
        is_robust, robustness_score = self._assess_robustness(
            best_backtest, mc, wf
        )

        # ─── Build Result ─────────────────────────────────────────
        opt_result = OptimizationResult(
            strategy_name=strategy_name,
            optimized_params=best_params,
            metrics={
                "trades": best_backtest.total_trades,
                "win_rate": best_backtest.win_rate,
                "profit_factor": best_backtest.profit_factor,
                "expectancy_r": best_backtest.expectancy_r,
                "total_pnl_r": best_backtest.total_pnl_r,
                "max_drawdown_r": best_backtest.max_drawdown_r,
                "sharpe_ratio": best_backtest.sharpe_ratio,
                "sortino_ratio": best_backtest.sortino_ratio,
                "avg_win_r": best_backtest.avg_win_r,
                "avg_loss_r": best_backtest.avg_loss_r,
                "max_consec_losses": best_backtest.max_consecutive_losses,
            },
            monte_carlo=mc if isinstance(mc, dict) else {},
            walk_forward=wf if isinstance(wf, dict) else {},
            is_robust=is_robust,
            robustness_score=robustness_score,
        )

        # Save
        self.store.save_optimization_result(opt_result)

        # Update rule with backtest status
        rule.backtested = True
        rule.backtest_metrics = opt_result.metrics
        self.store.save_strategy_rule(rule)

        return opt_result

    # ──────────────────────────────────────────────────────────────────
    #  Batch Optimization
    # ──────────────────────────────────────────────────────────────────

    def optimize_all(
        self,
        rules: List[StrategyRule],
        candles: List[dict],
        signal_funcs: Dict[str, Callable],
        htf_candles: Optional[List[dict]] = None,
    ) -> List[OptimizationResult]:
        """
        Optimize all strategy rules.

        Args:
            rules: List of StrategyRule from Agent 2
            candles: Historical data
            signal_funcs: {strategy_name: signal_function}
        """
        results = []
        for rule in rules:
            func = signal_funcs.get(rule.strategy_name)
            if not func:
                log.warning(f"No signal function for '{rule.strategy_name}', skipping")
                continue
            try:
                result = self.optimize_strategy(rule, candles, func, htf_candles)
                results.append(result)
            except Exception as e:
                log.error(f"Optimization failed for '{rule.strategy_name}': {e}")
                continue

        # Export combined report
        self._export_optimization_report(results)
        return results

    # ──────────────────────────────────────────────────────────────────
    #  Grid Search Optimizer
    # ──────────────────────────────────────────────────────────────────

    def _grid_search(
        self,
        candles: List[dict],
        signal_func: Callable,
        strategy_name: str,
        param_ranges: Dict[str, Tuple[float, float, float]],
    ) -> Tuple[Dict[str, float], BacktestResult]:
        """
        Grid search over parameter combinations.

        Returns:
            (best_params_dict, best_backtest_result)
        """
        # Generate parameter grid
        param_names = list(param_ranges.keys())
        param_values = []
        for name in param_names:
            low, high, step = param_ranges[name]
            values = list(np.arange(low, high + step / 2, step))
            param_values.append(values)

        # Limit grid size (max 500 combinations)
        total_combos = 1
        for v in param_values:
            total_combos *= len(v)

        if total_combos > 500:
            # Use random sampling
            return self._random_search(
                candles, signal_func, strategy_name,
                param_ranges, n_samples=200
            )

        best_score = -np.inf
        best_params = {}
        best_result = None

        for combo in itertools.product(*param_values):
            params = dict(zip(param_names, combo))
            try:
                result = self.backtester.run(
                    candles, signal_func, strategy_name, params
                )
                score = self._objective_score(result)
                if score > best_score:
                    best_score = score
                    best_params = params
                    best_result = result
            except Exception:
                continue

        if best_result is None:
            # Return defaults
            best_result = self.backtester.run(candles, signal_func, strategy_name, {})
            best_params = {}

        return best_params, best_result

    def _random_search(
        self,
        candles: List[dict],
        signal_func: Callable,
        strategy_name: str,
        param_ranges: Dict,
        n_samples: int = 200,
    ) -> Tuple[Dict[str, float], BacktestResult]:
        """Random search when grid is too large."""
        rng = np.random.default_rng(42)
        best_score = -np.inf
        best_params = {}
        best_result = None

        for _ in range(n_samples):
            params = {}
            for name, (low, high, step) in param_ranges.items():
                n_steps = int((high - low) / step) + 1
                idx = rng.integers(0, n_steps)
                params[name] = round(low + idx * step, 4)

            try:
                result = self.backtester.run(
                    candles, signal_func, strategy_name, params
                )
                score = self._objective_score(result)
                if score > best_score:
                    best_score = score
                    best_params = params
                    best_result = result
            except Exception:
                continue

        if best_result is None:
            best_result = self.backtester.run(candles, signal_func, strategy_name, {})

        return best_params, best_result

    def _objective_score(self, result: BacktestResult) -> float:
        """
        Multi-objective scoring function.
        Balances profitability, consistency, and risk.
        """
        if result.total_trades < 5:
            return -100  # penalize too few trades

        # Weighted composite
        score = (
            result.expectancy_r * 40 +          # primary: per-trade edge
            result.profit_factor * 10 +           # consistency
            result.win_rate * 20 +                # predictability
            result.sharpe_ratio * 5 +             # risk-adjusted
            -result.max_drawdown_r * 15 +         # penalize drawdown
            -result.max_consecutive_losses * 2 +  # penalize streaks
            min(result.total_trades, 50) * 0.5    # reward sample size (capped)
        )

        # Hard penalties
        if result.win_rate < MIN_WIN_RATE:
            score -= 20
        if result.profit_factor < MIN_PROFIT_FACTOR and result.profit_factor < float('inf'):
            score -= 15
        if result.expectancy_r < MIN_EXPECTANCY_R:
            score -= 25

        return score

    # ──────────────────────────────────────────────────────────────────
    #  Robustness Assessment
    # ──────────────────────────────────────────────────────────────────

    def _assess_robustness(
        self,
        backtest: BacktestResult,
        mc: Dict[str, Any],
        wf: Dict[str, Any],
    ) -> Tuple[bool, float]:
        """
        Assess overall strategy robustness.

        Returns:
            (is_robust: bool, robustness_score: 0-1)
        """
        score = 0.0
        checks = 0

        # Backtest metrics
        if backtest.win_rate >= MIN_WIN_RATE:
            score += 1
        checks += 1

        if backtest.profit_factor >= MIN_PROFIT_FACTOR:
            score += 1
        checks += 1

        if backtest.expectancy_r >= MIN_EXPECTANCY_R:
            score += 1
        checks += 1

        if backtest.total_trades >= 20:
            score += 1
        checks += 1

        # Monte Carlo
        if isinstance(mc, dict) and "error" not in mc:
            if mc.get("profit_probability", 0) >= 0.7:
                score += 1
            checks += 1

            if mc.get("ruin_probability", 1) <= 0.1:
                score += 1
            checks += 1

            if mc.get("p5_return_r", -999) > 0:
                score += 1
            checks += 1

        # Walk-forward
        if isinstance(wf, dict) and "error" not in wf:
            if wf.get("consistency_ratio", 0) >= 0.6:
                score += 1
            checks += 1

            if wf.get("performance_degradation", 1) <= 0.3:
                score += 1
            checks += 1

            if wf.get("avg_oos_expectancy", -1) > 0:
                score += 1
            checks += 1

        robustness = score / checks if checks > 0 else 0
        is_robust = robustness >= 0.6

        log.info(f"Robustness: {robustness:.1%} ({score}/{checks} checks) "
                 f"→ {'ROBUST' if is_robust else 'NOT ROBUST'}")

        return is_robust, round(robustness, 3)

    # ──────────────────────────────────────────────────────────────────
    #  Reporting
    # ──────────────────────────────────────────────────────────────────

    def _export_optimization_report(self, results: List[OptimizationResult]):
        """Export comprehensive optimization report."""
        report = {
            "generated_at": datetime.now().isoformat(),
            "total_strategies": len(results),
            "robust_strategies": sum(1 for r in results if r.is_robust),
            "strategies": []
        }

        for r in sorted(results, key=lambda x: x.robustness_score, reverse=True):
            report["strategies"].append({
                "name": r.strategy_name,
                "is_robust": r.is_robust,
                "robustness_score": r.robustness_score,
                "params": r.optimized_params,
                "metrics": r.metrics,
                "monte_carlo_summary": {
                    k: v for k, v in r.monte_carlo.items()
                    if k in ("median_return_r", "ruin_probability",
                             "profit_probability", "p95_max_dd_r")
                },
                "walk_forward_summary": {
                    k: v for k, v in r.walk_forward.items()
                    if k in ("consistency_ratio", "avg_oos_win_rate",
                             "performance_degradation")
                },
            })

        path = EXPORTS_DIR / "optimization_report.json"
        with open(path, "w") as f:
            json.dump(report, f, indent=2, default=str)
        log.info(f"Exported optimization report: {path}")

        # Human-readable summary
        txt_path = EXPORTS_DIR / "optimization_summary.txt"
        with open(txt_path, "w") as f:
            f.write("=" * 70 + "\n")
            f.write("AI STRATEGY OPTIMIZATION REPORT\n")
            f.write(f"Generated: {report['generated_at']}\n")
            f.write("=" * 70 + "\n\n")
            f.write(f"Total Strategies: {report['total_strategies']}\n")
            f.write(f"Robust Strategies: {report['robust_strategies']}\n\n")

            for s in report["strategies"]:
                robust_badge = "✅ ROBUST" if s["is_robust"] else "❌ NOT ROBUST"
                f.write(f"─── {s['name']} ── {robust_badge} "
                        f"({s['robustness_score']:.0%}) ───\n")
                m = s["metrics"]
                f.write(f"  Trades: {m.get('trades', 0)}  |  "
                        f"WR: {m.get('win_rate', 0):.1%}  |  "
                        f"PF: {m.get('profit_factor', 0):.2f}\n")
                f.write(f"  Expectancy: {m.get('expectancy_r', 0):.3f}R  |  "
                        f"Sharpe: {m.get('sharpe_ratio', 0):.2f}\n")
                f.write(f"  Max DD: {m.get('max_drawdown_r', 0):.2f}R  |  "
                        f"Total PnL: {m.get('total_pnl_r', 0):.1f}R\n")
                if s["params"]:
                    f.write(f"  Best Params: {s['params']}\n")
                mc = s.get("monte_carlo_summary", {})
                if mc:
                    f.write(f"  MC: Profit Prob={mc.get('profit_probability', 0):.1%}  "
                            f"Ruin={mc.get('ruin_probability', 0):.2%}\n")
                wf = s.get("walk_forward_summary", {})
                if wf:
                    f.write(f"  WF: Consistency={wf.get('consistency_ratio', 0):.1%}  "
                            f"Degradation={wf.get('performance_degradation', 0):.1%}\n")
                f.write("\n")

        log.info(f"Exported optimization summary: {txt_path}")

    def generate_optimized_config(
        self, results: List[OptimizationResult]
    ) -> Dict[str, Any]:
        """
        Generate an optimized configuration from all results.

        Returns a config dict that can be used to configure the live scanner.
        """
        config = {
            "generated_at": datetime.now().isoformat(),
            "strategies": {},
        }

        for r in results:
            if not r.is_robust:
                continue

            config["strategies"][r.strategy_name] = {
                "enabled": True,
                "params": r.optimized_params,
                "min_score": r.optimized_params.get("min_score", 5),
                "expected_win_rate": r.metrics.get("win_rate", 0),
                "expected_expectancy": r.metrics.get("expectancy_r", 0),
                "robustness_score": r.robustness_score,
            }

        path = EXPORTS_DIR / "optimized_config.json"
        with open(path, "w") as f:
            json.dump(config, f, indent=2)
        log.info(f"Exported optimized config: {path}")
        return config
