"use client";

import { useState } from "react";
import { usePathname } from "next/navigation";
import Sidebar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";
import MobileNav from "@/components/MobileNav";
import MarketCommandBar from "@/components/MarketCommandBar";
import BackendStatusNotice from "@/components/BackendStatusNotice";
import CommandPalette from "@/components/CommandPalette";
import MultiPanelLayout from "@/components/MultiPanelLayout";
import PublicAuthFrame from "@/components/PublicAuthFrame";
import { isPublicDashboardPath } from "@/lib/publicShell";

function Disclaimer() {
  return (
    <div
      style={{
        padding: "10px 16px",
        background: "rgba(0, 0, 0, 0.55)",
        borderTop: "1px solid rgba(255, 255, 255, 0.06)",
        fontSize: "0.64rem",
        lineHeight: 1.6,
        color: "rgba(255, 255, 255, 0.35)",
        textAlign: "center",
      }}
    >
      <strong style={{ color: "rgba(255, 255, 255, 0.5)" }}>Disclaimer:</strong>{" "}
      This platform is for <strong>educational and informational purposes only</strong>.
      Stocks With Gaurav is <strong>not SEBI-registered</strong> and does not provide
      investment advice. All information, analyses, and stock ideas are generated by
      automated algorithms and should not be construed as recommendations to buy, sell,
      or hold any security. Consult a qualified financial advisor before making
      investment decisions. Past performance does not guarantee future results.
      Market data sourced from NSE via yfinance and may be delayed up to 15 minutes.
      Investments in securities are subject to market risks — read all related documents
      carefully.
    </div>
  );
}

export default function LayoutClient({ children }: { children: React.ReactNode }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [terminalLayout, setTerminalLayout] = useState(false);
  const pathname = usePathname();

  if (pathname === "/") {
    return <>{children}</>;
  }

  if (isPublicDashboardPath(pathname) && pathname !== "/") {
    return <PublicAuthFrame>{children}</PublicAuthFrame>;
  }

  return (
    <div className="flex flex-1 min-w-0 overflow-x-hidden min-h-screen">
      <Sidebar
        isOpen={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
      />
      <div className="flex-1 flex flex-col min-w-0 relative z-[2] overflow-hidden">
        <MarketCommandBar />
        <BackendStatusNotice />
        <TopBar
          onMenuClick={() => setSidebarOpen((v) => !v)}
          terminalLayout={terminalLayout}
          onTerminalLayoutToggle={() => setTerminalLayout((v) => !v)}
        />
        <main className="flex-1 overflow-y-auto overflow-x-hidden p-4 pb-20 md:pb-6 md:p-6 lg:p-8">
          {terminalLayout ? <MultiPanelLayout /> : children}
        </main>
        <Disclaimer />
      </div>
      <MobileNav />
      <CommandPalette />
    </div>
  );
}
