# Schedule daily signal archiving — runs once after market close every weekday.
# Run this script ONCE to register the Windows Task Scheduler task.
# After that, signals are archived automatically to signal_history/signals_YYYY.csv
# and committed + pushed to GitHub every trading day at 4:30 PM.

$python  = "C:\Users\g6666\Trading Algo\.venv\Scripts\python.exe"
$script  = "C:\Users\g6666\Trading Algo\scripts\archive_signals.py"
$workdir = "C:\Users\g6666\Trading Algo"
$pypath  = "C:\Users\g6666\Trading Algo"
$gitexe  = "git"

# ── We run the Python archiver + git commit + push via a helper ps1 ─────────
# (Task Scheduler can only call one executable directly; the helper wraps both steps)
$helperPath = "C:\Users\g6666\Trading Algo\scripts\archive_and_push.ps1"

# Write the helper script dynamically so paths are always absolute
$helperContent = @"
# Auto-generated by SCHEDULE_SIGNAL_ARCHIVE.ps1 — do not edit manually
Set-Location "$workdir"

Write-Output "[Archive] Starting signal archive - `$(Get-Date -Format 'yyyy-MM-dd HH:mm')"

# 1. Pull latest from origin so git push won't conflict
& git pull --rebase origin main 2>&1 | Write-Output

# 2. Run archiver
& "$python" "$script" --days 30 2>&1 | Write-Output

# 3. Stage, commit and push if anything changed
& git add signal_history/ 2>&1 | Write-Output
`$status = & git status --porcelain signal_history/
if (`$status) {
    `$dateTag = Get-Date -Format "yyyy-MM-dd"
    & git commit -m "archive: auto signal history `$dateTag" 2>&1 | Write-Output
    & git push origin main 2>&1 | Write-Output
    Write-Output "[Archive] Committed and pushed signal history for `$dateTag"
} else {
    Write-Output "[Archive] Nothing new to commit"
}
"@

# Write helper to disk
[System.IO.File]::WriteAllText($helperPath, $helperContent, [System.Text.Encoding]::UTF8)
Write-Host "Helper script written: $helperPath" -ForegroundColor Cyan

# ── Register Task Scheduler task ─────────────────────────────────────────────
$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NonInteractive -ExecutionPolicy Bypass -File `"$helperPath`"" `
    -WorkingDirectory $workdir

# 4:30 PM Mon–Fri (30 min after market close + options expiry checks done)
$trigger = New-ScheduledTaskTrigger -Weekly `
    -DaysOfWeek Monday,Tuesday,Wednesday,Thursday,Friday `
    -At "04:30PM"

$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 15) `
    -StartWhenAvailable `          # Run on next opportunity if PC was off at 4:30
    -RunOnlyIfNetworkAvailable     # Need internet to reach Railway + GitHub

Register-ScheduledTask `
    -TaskName   "StocksWithGaurav_ArchiveSignals" `
    -Action     $action `
    -Trigger    $trigger `
    -Settings   $settings `
    -RunLevel   Highest `
    -Description "Archives daily trade signals from Railway to GitHub (signal_history/signals_YYYY.csv)" `
    -Force | Out-Null

Write-Host ""
Write-Host "✅ Task registered: StocksWithGaurav_ArchiveSignals" -ForegroundColor Green
Write-Host "   Schedule : 4:30 PM, Monday–Friday" -ForegroundColor Green
Write-Host "   Archives : signal_history\signals_$(Get-Date -Format 'yyyy').csv" -ForegroundColor Green
Write-Host "   Git push : origin/main" -ForegroundColor Green
Write-Host ""
Write-Host "To run it manually right now:" -ForegroundColor Yellow
Write-Host "  Start-ScheduledTask -TaskName StocksWithGaurav_ArchiveSignals"
Write-Host ""
Write-Host "To remove the task later:" -ForegroundColor Yellow
Write-Host "  Unregister-ScheduledTask -TaskName StocksWithGaurav_ArchiveSignals -Confirm:$" + "false"
